guidebooks/store

- guidebooks/kubernetes/kubectl.md
This is copied from @mra-ruiz knative docs repo.
> doc: add kubectl guidebook

- guidebooks/docker/docker.md
This content comes from @mra-ruiz knative docs repo
> doc: add docker guidebook

- guidebooks/kubernetes/kind.md
- guidebooks/kubernetes/minikube.md
This content comes from @mra-ruiz knative/docs repo
> doc: add kind and minikube guidebooks

- guidebooks/knative/install/plugin/quickstart.md
- guidebooks/knative/install/plugin/wizard.md
Created a folder "install-knative-using-plugin" to contain all files necessary for this guidebook
> doc: add install-knative-using-plugin guidebook and supporting files

- .gitignore
Suggesting that we ignore these two types of files
> doc: Adding .gitignore file

- guidebooks/ibm/cloud/target.md
Use a per-choice validator, and a guidebook-wide validator
> fix: refine the validation logic for ibm/cloud/target

- guidebooks/ibm/cloud/ce/project.md
we had a jq filter with single = rather than ==
> fix: ibm/cloud/ce/project has buggy expand and missing import for clis/ce

- guidebooks/ibm/cloud/ce/project.md
- guidebooks/kubernetes/helm3.md
- guidebooks/ml/codeflare/training/bert.md
- guidebooks/ml/ray/install/index.md
- guidebooks/ml/ray/install/kubernetes.md
- guidebooks/python/conda/install.md
- guidebooks/python/conda/what-is-conda.md
- helm3.md
- ray/install
- condo/install
> doc: begin to flesh out ml guidebooks

- guidebooks/ml/ray/run/examples/dataset/create/from-file.md
- guidebooks/python/pip/tqdm.md
> feat: update ml/ray/run/examples/dataset/create/from-file to use tqdm

- guidebooks/ml/ray/install/data.md
- guidebooks/ml/ray/install/index.md
- guidebooks/ml/ray/install/kubernetes.md
- guidebooks/ml/ray/install/serve.md
- guidebooks/ml/ray/install/tune.md
- guidebooks/ml/ray/run/core/actors.md
- guidebooks/ml/ray/run/core/tasks.md
- guidebooks/ml/ray/run/data/create/from-file.md
- guidebooks/ml/ray/run/data/create/from-range.md
- guidebooks/ml/ray/run/serve/examples/gradient-boosting.md
- guidebooks/ml/ray/run/train/examples/pytorch/index.md
- guidebooks/ml/ray/run/tune/examples/grid-search.md
- guidebooks/python/pip/aiorwlock.md
- guidebooks/python/pip/fastapi.md
- guidebooks/python/pip/pyarrow.md
- guidebooks/python/pip/scikit-learn.md
- guidebooks/python/pip/tabulate.md
- guidebooks/python/pip/tensorboard.md
- guidebooks/python/pip/torch.md
- guidebooks/python/pip/tqdm.md
- guidebooks/python/pip/uvicorn.md
This should let us run ray jobs against a remote cluster.
> doc: updates to use new pip-show and ray-submit executors

- guidebooks/ml/ray/run/core/tasks.md
> fix: ml/ray/run/core/tasks should stream out logs

- guidebooks/ml/ray/start/kubernetes.md
This PR fixes a few race conditions, e.g. between helm install and ray head node existence and ray worker node existence.
TODO: there is still an issue with waiting for worker nodes. As written, we will wait for *all* worker nodes to be ready. Perhaps we should find a way to wait for at least one to be ready? We are using a `kubectl wait pod --label-selector=...`, and apparently `kubectl` treats a label-selector-based wait as a "wait for all". :/
> fix: improve robustness of ml/ray/start/kubernetes

- guidebooks/ml/ray/start/kubernetes.md
this pr also adds event streaming
> fix: try to avoid "no matching resources" in ml/ray/start/kubernetes

- guidebooks/ml/codeflare/training/bert/index.md
- guidebooks/ml/codeflare/training/bert/ray-bert-vanilla.py
- guidebooks/ml/codeflare/tuning/glue/index.md
- guidebooks/ml/codeflare/tuning/hap/index.md
- guidebooks/ml/ray/run/logs.md
- guidebooks/ml/ray/start/kubernetes.md
- guidebooks/ml/ray/start/kubernetes/port-forward.md
- guidebooks/ml/ray/stop/kubernetes.md
- guidebooks/ml/tensorflow/tensorboard/rsync.md
- guidebooks/ml/tensorflow/tensorboard/run.md
- guidebooks/python/pip/tensorflow.md
- guidebooks/util/open-url.md
and some surrounding utilities to make it happen
> feat: add tensorboard support to ml/codeflare/training/bert

- guidebooks/ibm/cloud/cos/auth.md
- guidebooks/ibm/cloud/cos/instance.md
- guidebooks/knative/provision/cluster/index.md
- guidebooks/knative/provision/cluster/serving/with-yaml.md
- guidebooks/knative/provision/quickstart/index.md
- guidebooks/ml/codeflare/training/bert/index.md
- guidebooks/ml/codeflare/tuning/glue/index.md
- guidebooks/ml/codeflare/tuning/hap/index.md
- guidebooks/ml/ray/run/core/index.md
- guidebooks/ml/ray/run/core/tasks.md
- guidebooks/ml/ray/run/data/create/index.md
- guidebooks/ml/ray/run/data/index.md
- guidebooks/ml/ray/run/index.md
- guidebooks/ml/ray/run/logs.md
- guidebooks/ml/ray/run/serve/index.md
- guidebooks/ml/ray/run/train/examples/pytorch/index.md
- guidebooks/ml/ray/run/train/index.md
- guidebooks/ml/ray/run/tune/index.md
- guidebooks/ml/ray/start/index.md
- guidebooks/python/conda/install.md
now, relative paths need to be ./ or ../ prefixed
> chore: update to madwizard 0.9.0's relative path breaking change

- guidebooks/ml/codeflare/tuning/glue/conda.txt
- guidebooks/ml/codeflare/tuning/glue/glue_benchmark.py
- guidebooks/ml/codeflare/tuning/glue/pip.txt
1) it needs a specific version of transformers==3.0.2
2) it needs ray_lightning and pytorch_lightning
> fix: ml/codeflare/tuning/glue has missing dependencies

- guidebooks/ml/codeflare/tuning/glue/pip.txt
transformers=3.0.2 -> transformers==3.0.2
> fix: incorrect syntax for ml/codeflare/tuning/glue/pip.txt

- guidebooks/s3/install/auth.md
> fix: increase verbosity of s3/install/auth

- guidebooks/aws/auth.md
we were only setting S3_... env vars
> fix: in aws/auth, also set AWS_... env vars

- guidebooks/ml/ray/start/kubernetes.md
> chore: update ml/ray/start/kubernetes to use canonical store import paths

- guidebooks/s3/choose/_bucket.md
- guidebooks/s3/create/bucket.md
- guidebooks/util/separator.md
and move create bucket to the bottom
> feat: add separator to s3/choose/bucket

- guidebooks/ml/ray/run/gpu-utilization.sh
> Revert "feat: add gpu total memory to gpu utilization stream"

- guidebooks/ml/ray/start/kubernetes.md
- guidebooks/ml/ray/start/kubernetes/install-via-helm.md
- guidebooks/ml/ray/start/kubernetes/port-forward.md
this PR factors the helm install part into its own guidebook ml/ray/start/kubernetes/install-via-helm
> fix: clean up ml/ray/start/kubernetes messages and code

- guidebooks/ml/codeflare/tuning/glue/glue_benchmark.py
to make it easier to parse, and to more clearer delineate start and end events
> feat: update ml/codeflare/tuning/glue to improve logging of data fetches

- guidebooks/ml/codeflare/job/log/init/s3.md
- guidebooks/ml/codeflare/training/bert/index.md
- guidebooks/ml/codeflare/training/bert/ray-bert-vanilla.py
- guidebooks/ml/ray/aggregator/index.md
- guidebooks/ml/ray/aggregator/setup.md
- guidebooks/ml/ray/cluster/index.md
- guidebooks/ml/ray/cluster/kubernetes.md
- guidebooks/ml/ray/cluster/local.md
- guidebooks/ml/ray/run/choose.md
- guidebooks/ml/ray/run/gpu-utilization.md
- guidebooks/ml/ray/run/logs/init.md
- guidebooks/ml/ray/run/pod-stats.md
- guidebooks/ml/ray/start/kubernetes.md
- guidebooks/ml/ray/start/kubernetes/label-selectors.md
a bit of refactoring to allow for separate spawning of the log aggregation portion
> feat: separate ml/ray/aggregator for log aggregation

- guidebooks/ml/ray/run/job-definition.md
> fix: ml/ray/run/job-definition uses >> but should use >

- guidebooks/ml/ray/run/gpu-utilization.sh
- guidebooks/ml/ray/run/index.md
- guidebooks/ml/ray/run/job-definition.md
- guidebooks/ml/ray/run/node-stats.sh
- guidebooks/ml/ray/run/pod-stats.sh
- guidebooks/ml/ray/run/pod-vmstat-memory.sh
- guidebooks/ml/ray/run/pod-vmstat.sh
- guidebooks/ml/ray/start/local.md
some of the data collectors that are kube-specific need to be guarded
> fix: improvements for ml/ray/run against a local cluster

- guidebooks/ml/ray/start/kubernetes/install-via-helm.md
use namespaced operator via helm and note cluster scoped
> feat: use namespaced operator

- guidebooks/ml/ray/aggregator/index.md
- guidebooks/ml/ray/aggregator/setup.md
- guidebooks/ml/ray/aggregator/with-jobid.md
- guidebooks/ml/ray/cluster/connect.md
- guidebooks/ml/ray/cluster/kubernetes/index.md
- guidebooks/ml/ray/start/local.md
This PR also adds ml/ray/cluster/connect to allow provisioning a RAY_ADDRESS
> feat: ml/ray/aggregator updates to support late-connect with given jobId

- guidebooks/ml/ray/aggregator/setup.md
Also RAY_ADDRESS. You should now see messages like:
> Please set JOB_ID
or
> Please set RAY_ADDRESS
> fix: ml/ray/aggregator/with-jobid should fail gracefully if JOB_ID not defined

- guidebooks/ml/ray/aggregator/in-cluster.md
For in-cluster launching of the log aggregator.
> feat: add `ml/ray/aggregator/in-cluster`

- guidebooks/ml/ray/aggregator/in-cluster.md
Rather than making it a choice, because, in-cluster, it is a fixed value.
> fix: ml/ray/aggregator/in-cluster should infer KUBE_NS

- guidebooks/ml/ray/aggregator/in-cluster/client-side/aggregator.yaml
- guidebooks/ml/ray/aggregator/in-cluster/server-side/setup.md
This PR also changes LOG_AGGREGATOR_POD to LOG_AGGREGATOR_POD_NAME to make it consistent with the rest of the code
> fix: avoid hard-coded ray cluster name in ml/ray/aggregator/in-cluster

- guidebooks/ml/ray/aggregator/in-cluster/client-side/aggregator.yaml
- guidebooks/ml/ray/aggregator/in-cluster/client-side/start/ask-server-to-start.md
> fix: improve debuggability of server-side log aggregation

- guidebooks/ml/ray/aggregator/setup.md
TODO: find a home for wait-and-cat script
> fix: client-side of in-cluster aggregator needs to wait for job env file to exist

- guidebooks/ml/ray/aggregator/in-cluster/server-side/setup.md
- guidebooks/ml/ray/run/logs/init.md
> feat: server-side log aggregator should only launch itself once

- guidebooks/ml/ray/run/logs/init.md
this feature appeared in madwizard 0.19.0
> feat: update to new "early exit" (exit code 90) for aggregator singleton

- guidebooks/ml/ray/cluster/kubernetes/choose-pod-scheduler.md
> fix: minor wordsmithing to ml/ray/cluster/kubernetes/choose-pod-scheduler

- guidebooks/ml/ray/start/kubernetes/chart/templates/_head-deployment.tpl
- guidebooks/ml/ray/start/kubernetes/chart/values.yaml
- guidebooks/ml/ray/start/kubernetes/install-via-helm.sh
For now: RAY_STARTUP_PROBE_INITIAL_DELAY_SECONDS
> feat: allow ray helm chart startup probe values to be injected via env vars

- guidebooks/kubernetes/mcad/install/mcad.sh
> feat: allow mcad resource requirements to be dialed down when running CI

- guidebooks/ml/ray/start/kubernetes/chart/templates/_head-deployment.tpl
this helps with pip and conda setup times
> fix: increase cpu limit for ray head

- guidebooks/util/jobid.md
- package-lock.json
- package.json
Requires https://github.com/guidebooks/madwizard/pull/407
`madwizard >= 0.19.5`
> fix: util/jobid should inherit JOB_ID from env

- guidebooks/ml/ray/aggregator/in-cluster/client-side/start/setup-local-stream.md
- guidebooks/ml/ray/aggregator/in-cluster/client-side/start/stream-to-local.md
TODO: we need to find a way to know the home directory of the container
> fix: ugh, ~/ -> /root for server-side log aggregator

- guidebooks/ml/codeflare/training/demos/getting-started/index.md
- guidebooks/ml/codeflare/training/demos/getting-started/main.py
- guidebooks/ml/codeflare/training/demos/getting-started/requirements.txt
- guidebooks/ml/codeflare/training/demos/index.md
a non-gpu, non-s3, super simple demo
> feat: add ml/codeflare/training/demos/getting-started

- guidebooks/ml/codeflare/training/roberta/choose-data-s3fs.md
- guidebooks/ml/codeflare/training/roberta/choose-data.md
- guidebooks/ml/codeflare/training/roberta/pvc.yaml
- guidebooks/ml/codeflare/training/roberta/s3fs.md
- guidebooks/ml/codeflare/training/roberta/wrapper.sh
- guidebooks/ml/ray/start/kubernetes/chart/templates/_worker-deployment.tpl
- guidebooks/ml/ray/start/kubernetes/chart/values.yaml
- guidebooks/ml/ray/start/kubernetes/install-via-helm.sh
This PR also updates the ray helm chart to support volume mounts from pvcs
> feat: support for s3fs in ml/codeflare/training/roberta

- guidebooks/ml/codeflare/training/demos/getting-started/main.py
- guidebooks/ml/codeflare/training/demos/getting-started/requirements.txt
- guidebooks/ml/codeflare/training/demos/getting-started/s3.md
this is a variant of ml/codeflare/training/demos/getting-started that supports pulling the mnist.npz data from s3
> feat: add ml/codeflare/training/demos/getting-started/s3

- guidebooks/ml/ray/start/resources.md
hopefully for a better out of the box experience.
> fix: adjust default ray cluster resources to be less demanding

- guidebooks/ml/ray/start/kubernetes/chart/templates/_head-deployment.tpl
- guidebooks/ml/ray/start/kubernetes/chart/templates/_worker-deployment.tpl
openshift local seems to require or at least desire this
> fix: enforce more restrictive securityContext for ray pods

- guidebooks/ml/ray/start/index.md
We have no tests for ray running locally
> feat: discontinue support for ray local (ray kube only)

- guidebooks/kubernetes/choose/ns-with-context.md
- guidebooks/kubernetes/choose/ns.md
This PR also refactors the existing kubernetes/choose/ns to use kubernetes/choose/ns-with-context under the covers
> feat: add kubernetes/choose/ns-with-context to allow choice of ns with an a priori context choice

- guidebooks/ml/codeflare/training/bert/index.md
- guidebooks/ml/codeflare/training/bert/submit.md
- guidebooks/ml/ray/start/kubernetes/install-via-helm.md
- guidebooks/ml/ray/v1.md
Also update ml/codeflare/training/bert to use that, and also to bring down ray when done
> feat: add ml/ray/v1 to allow use cases to insist on using ray v1

- guidebooks/ml/ray/cluster/choose/kubernetes.md
- package-lock.json
- package.json
This allows ml/ray/start to define the cluster to be stopped via ml/ray/stop
> feat: update ml/ray/cluster/choose to use madwizard env-keyed choice

- guidebooks/ml/ray/run/choose/v1.md
- guidebooks/ml/ray/run/choose/v2.md
And also offer a "i don't see my job, exit now" option
> fix: ml/ray/run/choose should wait a bit for ray job to be active

- guidebooks/ml/ray/cluster/head.md
- guidebooks/ml/ray/cluster/kubernetes/index.md
- guidebooks/ml/ray/start/kubernetes.md
- guidebooks/ml/ray/start/kubernetes/events.md
- guidebooks/ml/ray/start/kubernetes/install-via-helm.md
- guidebooks/ml/ray/start/kubernetes/invoke-helm.md
- guidebooks/ml/ray/start/kubernetes/name.md
- guidebooks/ml/ray/start/kubernetes/wait-for-workers.md
factorize the parts better so we can use imports not inlining fix bug in ml/ray/cluster/head -- it wasn't using the context and ns state
> feat: clean up ml/ray/start/kubernetes

- guidebooks/ml/codeflare/training/byoc/index.md
- guidebooks/ml/ray/start/kubernetes.md
- guidebooks/ml/ray/start/kubernetes/chart/templates/_head-deployment.tpl
- guidebooks/ml/ray/start/kubernetes/chart/values.yaml
- guidebooks/ml/ray/start/kubernetes/self-destruct/index.md
- guidebooks/ml/ray/start/kubernetes/self-destruct/self-destruct.yaml
This adds the capability for the helm chart to self-destruct upon job completion, via an in-cluster job
> feat: ray helm chart should tear itself down when job completes

- guidebooks/ml/ray/start/kubernetes/install-via-helm.sh
This also improves the log output to be more consistent.
> fix: improved error handling in helm install for lack of cluster name

- guidebooks/ml/ray/start/kubernetes/invoke-helm.md
Tell the user it is safe to disconnect.
> fix: improve messaging after ray job submit

- guidebooks/ml/torchx/run/stop.md
- guidebooks/ml/torchx/run/wait-till-running.md
this also cleans up the output a bit
> fix: ml/torchx/run/stop fails to delete helm

- guidebooks/ml/ray/start/kubernetes/chart/templates/pvc.yaml
- guidebooks/ml/torchx/run/start.sh
- guidebooks/s3/choose/_bucket.md
- guidebooks/s3/choose/s3fs/kubernetes/configure.md
- guidebooks/s3/choose/s3fs/kubernetes/folder.md
- guidebooks/s3/choose/s3fs/kubernetes/index.md
- guidebooks/s3/choose/s3fs/kubernetes/init.md
- package-lock.json
- package.json
BREAKING CHANGE: this updates s3/choose/bucket from single-select to multi-select, which may require re-selecting this choice
> feat: support for selecting multiple s3 buckets

- guidebooks/ml/ray/start/kubernetes/wait-for-head.md
- guidebooks/ml/ray/start/kubernetes/wait-for-workers.md
ugh, the sleep 1 is in the wrong place
this also cleans things up to avoid the poll-then-wait
> fix: ml/raay/start/kubernetes/wait-for-head/workers cpu spin

- guidebooks/ml/ray/start/kubernetes/wait-for-head.md
- guidebooks/ml/ray/start/kubernetes/wait-for-workers.md
run with DEBUG_KUBERNETES=true
> fix: improve debuggability of ray head crashes

- guidebooks/ml/codeflare/training/byoc/ctrlc.md
- guidebooks/ml/codeflare/training/byoc/index.md
- guidebooks/ml/torchx/run/ctrlc.md
- guidebooks/ml/torchx/run/index.md
> Revert "feat: ml/codeflare/training/byoc and ml/torchx/run should not kill on ctrl+c"

- guidebooks/ibm/cloud/login.md
- package-lock.json
- package.json
https://github.com/guidebooks/madwizard/pull/695
> fix: bump to madwizard@8 to adopt shell.stdin convention

- guidebooks/ml/ray/start/kubernetes/custodian/custodian.yaml
- guidebooks/ml/ray/start/kubernetes/custodian/index.md
- guidebooks/ml/ray/start/kubernetes/custodian/resources/cpu.awk
- guidebooks/ml/ray/start/kubernetes/custodian/resources/cpu.sh
- guidebooks/ml/ray/start/kubernetes/custodian/resources/memory.awk
- guidebooks/ml/ray/start/kubernetes/custodian/resources/memory.sh
This also fixes pod/pod/... in cpu streams
> feat: add memory utilization pod to custodian

- guidebooks/ml/ray/run/logs/via-exec.md
> Revert "fix: avoid use of all-containers in ray log streamer"

- guidebooks/ml/codeflare/custodian/containers/logs/container.yaml
- guidebooks/ml/codeflare/custodian/image.md
- guidebooks/ml/ray/run/logs/via-exec.md
- guidebooks/ml/ray/run/runtime-env-agent.sh
- guidebooks/ml/ray/run/runtime-env-setup.sh
- guidebooks/ml/ray/start/kubernetes/chart/templates/_head-deployment.tpl
- guidebooks/ml/ray/start/kubernetes/port-forward/ray-with-cluster.md
we have a few places that are doing `kubectl logs`, without protection against network disconnects
> fix: restore helm delete and increase resilience to network disconnects

- guidebooks/ml/codeflare/custodian/containers/cpu/cpu.awk
- guidebooks/ml/codeflare/custodian/containers/cpu/cpu.sh
This also adds a CPU Throttling metric.
> fix: cpu utilization information may be bogus; switch to cgroup-based stats

- guidebooks/ml/codeflare/custodian/containers/cpu/cpu.sh
- guidebooks/ml/codeflare/custodian/containers/gpu/gpu.sh
- guidebooks/ml/codeflare/custodian/containers/mem/memory.sh
- guidebooks/ml/codeflare/custodian/containers/runtime-env/runtime-env-setup.sh
- guidebooks/ml/codeflare/custodian/containers/status/worker-status.sh
- guidebooks/ml/ray/run/logs/via-exec.md
custodian should detect head pod existence
logs/via-exec shouldn't bother to tee to local file
> fix: more EOF protection fixes
