guidebooks/store

guidebooks/knative/provision/serving/with-yaml.md

This PR also removes the commented-out includes, due to a bug in kui with multi-line comments and snippet inlining.

doc: update knative serving with-yaml to use an import of kubectl

---

guidebooks/knative/provision/serving/with-yaml.md

Updated code blocks that used `{{artifact()}}` format to now use URLs.

doc: Using URLs instead of {{artifact()}} format

---

guidebooks/ibm/cloud/cli/ibmcloud.md
guidebooks/ibm/cloud/cli/plugins/cloud-object-storage.md
guidebooks/ibm/cloud/cli/plugins/codeengine.md
guidebooks/ibm/cloud/login.md
guidebooks/ibm/cloud/target.md

this will match everything in every imported guidebook

fix: various guidebooks have a topmatter codeblock match of .*

---

guidebooks/ibm/cloud/ce/job/run.md

this is due to a bug in the `ibmcloud ce` plugin

fix: increase sleep delay in ibm/cloud/ce/job/run

---

guidebooks/ml/codeflare/training/bert/index.md

This PR also fixes the validator, and uses the datapath and modelpath arguments, pointing them to /tmp

doc: update bert to use conda run

---

guidebooks/ml/ray/install/index.md
guidebooks/python/pip/pyarrow.md

it seems to be a lot faster to do a `python3 -c "import foo"` versus `pip show foo`. perhaps 2x faster? saving 500ms?

fix: avoid using "pip show" for validator

---

guidebooks/ml/ray/run/examples/index.md

This should have been removed in https://github.com/guidebooks/store/pull/74

chore: remove crufty ml/run/run/examples

---

guidebooks/ibm/cloud/cos/instance.md

the python boto3 client does not seem to like it with trailing dots, sigh

fix: remove trailing dot from IBM Cloud Object Storage endpoint urls

---

guidebooks/ml/ray/run/logs.md

it combines `shell.async` with a shell `&` fork, which means we can't manage the process's lifecycle

fix: nvidia-smi gpu utilization extractor uses & in shell script

---

guidebooks/ml/codeflare/training/bert/index.md

this is now part of the base ml/ray/start/kubernetes

fix: remove uid-range import from ml/codeflare/training/ber

---

guidebooks/ml/codeflare/tuning/glue/conda.txt
guidebooks/ml/codeflare/tuning/glue/glue_benchmark.py
guidebooks/ml/codeflare/tuning/glue/index.md
guidebooks/ml/codeflare/tuning/glue/overrides.md
guidebooks/ml/codeflare/tuning/glue/pip.txt

rather than relying on a custom base image
This PR also updates the `glue_benchmark.py` to set `num_gpus` depending on the `NUM_GPUS` environment variable, rather than hard-coding it to `1`

feat: update ml/codeflare/tuning/glue to use runtime_env dependence injection

---

guidebooks/s3/install/cli.md

`which aws` should be `which mc`

fix: s3/install/cli has a buggy validator

---

guidebooks/kubernetes/choose/ns.md
guidebooks/ml/ray/start/kubernetes.md

1) choosing a namespace; no need to do this if we haven't chosen a context
2) validating a previously started ray cluster in kube; no need to do this if we haven't chosen either a context or a namespace

fix: optimize kubernetes validation tasks

---

guidebooks/ml/codeflare/training/bert/index.md
guidebooks/ml/codeflare/training/bert/ray-bert-vanilla.py
guidebooks/ml/codeflare/training/bert/requirements.txt
guidebooks/ml/codeflare/tuning/glue/choose-glue-data.md
guidebooks/ml/codeflare/tuning/glue/choose-model.md
guidebooks/ml/codeflare/tuning/glue/index.md
guidebooks/ml/ray/hacks/openshift/uid-range.md
guidebooks/ml/ray/run/logs-in-s3.md
guidebooks/ml/ray/start/local.md
guidebooks/ml/tensorflow/tensorboard/run.md
guidebooks/s3/choose/_bucket.md
guidebooks/s3/choose/_object.md
guidebooks/s3/choose/bucket.md
guidebooks/s3/choose/object.md
guidebooks/s3/choose/prereqs.md

This PR leverages that and related s3 improvements for
1) ml/codeflare/training/bert: store tensorboard events in s3
2) ml/codeflare/training/glue: choose glue-data and model
This PR also fixes aggressive validation checks in ml/ray/hcks/openshift/uid-range. We don't need to bother with potentially expensive kubectl operations if KUBE_CONTEXT and KUBE_NS are not defined. That guidebook was also not using KUBE_CONTEXT In its kubectl commands.

fix: allow for multiple s3 object selections

---

guidebooks/ml/ray/start/kubernetes/port-forward.md

1) does not import context and namespace choosers
2) uses the non-default ray cluster name
3) exits immediately

fix: ml/ray/start/kubernetes/port-forward does not operate standalone

---

guidebooks/ml/codeflare/job/log/init/s3.md
guidebooks/ml/codeflare/training/bert/index.md
guidebooks/ml/codeflare/tuning/glue/choose-bucket.md
guidebooks/ml/codeflare/tuning/glue/choose-glue-data.md
guidebooks/ml/codeflare/tuning/glue/choose-model.md
guidebooks/ml/codeflare/tuning/glue/index.md
guidebooks/ml/ray/run/gpu-utilization.sh
guidebooks/ml/ray/run/logs-websocat.md
guidebooks/ml/ray/run/logs.md
guidebooks/ml/ray/run/logs.sh
guidebooks/ml/ray/start/kubernetes.md
guidebooks/util/websocat.md

note: ray job logs --follow does not coopeate with | tee, so we need to use websocat for now
https://discuss.ray.io/t/ray-job-logs-follow-does-not-cooperate-with-unix-pipes

fix: allow capturing of ray run logs to a local staging directory

---

guidebooks/ml/codeflare/job/log/init/s3.md

this avoids showing some commentary in a madwizard run that is only relevant to the guidebook developer

fix: move a bash comment into a markdown sentence

---

guidebooks/ml/ray/start/kubernetes.md

it doesn't always detect when the ray cluster does not yet exist

fix: validator for ml/ray/start/kubernetes has false negatives

---

guidebooks/ml/ray/run/logs.md
guidebooks/ml/ray/run/node-stats.md
guidebooks/ml/ray/run/node-stats.sh

a bit ugly, with the timestamp at the beginning, but i couldn't see a way to do this more gracefully -- i.e. integrate a timestamp with the underlying info that comes from `kubectl`. Using `kubectl get node --watch` would only give us updates on change to the underlying resource. Whereas we want to track this as MemFree, etc. the Free stats change.
```
2022-06-20 19:46:13	 NAME                           GPUCap   GPUFree   CPUCap   CPUFree   MemCap       MemFree      DiskCap       DiskFree       Type
2022-06-20 19:46:13	 ip-10-0-131-199.ec2.internal   <none>   <none>    2        1500m     8149576Ki    6998600Ki    125293548Ki   115470533646   m4.large
2022-06-20 19:46:13	 ip-10-0-131-59.ec2.internal    <none>   <none>    4        3500m     16407104Ki   15256128Ki   125293548Ki …
```

feat: ml/ray/run/logs should track node utilization stats

---

guidebooks/ml/ray/run/node-stats.sh

1) use ISO timestamps
2) don't repeat the timestamp for each row, i think this will be too hard to parse
```
NodeStats 2022-06-20T20:41:53-04:00
NAME             GPUCap   GPUFree   CPUCap   CPUFree   MemCap       MemFree      DiskCap       DiskFree      Type
10.186.206.229   <none>   <none>    4        3910m     16260832Ki   13484768Ki   103078840Ki   94369515442   b3c.4x16.encrypted
10.186.206.230   <none>   <none>    4        3910m     16253388Ki   13477324Ki   103078840Ki   94369515442   b3c.4x16.encrypted
NodeStats 2022-06-20T20:41:53-04:00
NAME             GPUCap   GPUFree   CPUCap   CPUFree   MemCap       MemFree      DiskCap       DiskFree      Type
10.186.206.229   <none>   <none>    4        3910m     16260832Ki   13484768Ki   103078840Ki   94369515442   b3c.4x16.encrypted …
```

feat: update ml/ray/run/node-stats syntax to use ISO dates

---

guidebooks/kubernetes/context.md

we can avoid setting global state, because madwizard can flow through state just for a given run

fix: kubernetes/context should not set global kube context

---

guidebooks/ml/codeflare/index.md
guidebooks/ml/codeflare/training/index.md
guidebooks/ml/codeflare/tuning/index.md

Nothing in the code blocks, just in the titles and expositions.

fix: clean up ml/codeflare titles and descriptions

---

guidebooks/ml/ray/start/kubernetes.md
guidebooks/ml/ray/start/kubernetes/install-via-helm.md

1. the helm upgrade command was not using the KUBE_CONTEXT variable
2. update to use IfNotPresent image pull policy
3. allow for a different operatorImage from head/worker images
4. upgrade from ray 1.12.2 to 1.13.0 for default base image

fix: ml/ray/start/kubernetes via helm fixes

---

guidebooks/ml/ray/run/gpu-utilization.sh
guidebooks/ml/ray/run/pod-stats.md
guidebooks/ml/ray/run/pod-vmstat-memory.sh

1) we were only collecting gpu utilization for the first pod
2) our vmstat metrics for memory are insufficient for containerized workloads; this PR improves the tracking of both total and consumed memory

feat: improve pod memory stats, and increase xargs concurrency

---

guidebooks/kubernetes/helm3.md

$/dev/fd/63: No such file or directory

fix: kubernetes/helm3 fails in docker container

---

guidebooks/util/jq.md

For now, this support is specific to Debian/Ubuntu

feat: add linux support to util/jq

---

guidebooks/ml/ray/run/gpu-utilization.sh
guidebooks/ml/ray/run/logs-websocat.md
guidebooks/ml/ray/run/logs.md

This PR adds:
- QUIET_CONSOLE: don't emit to the console, just direct to files
- NO_WAIT: don't wait for the job to finish

feat: update some of the ml/ray/run log aggregators to support not teeing to the console

---

guidebooks/ml/codeflare/index.md
guidebooks/ml/codeflare/run.md
guidebooks/ml/codeflare/welcome.md

Previously, the ml/codeflare/index.md guidebook was about running a job. This PR renames that to run.md, and slots in a new index.md where running a job is just one of several options (attach dashboard, ...)

feat: new ml/codeflare top-level guidebook

---

guidebooks/ml/ray/run/logs/init.md

instead of using a `mktemp -d` variable for the LOGDIR_STAGE of ml/ray/run/logs

feat: leverage new GUIDEBOOK_PROFILE_DATA env var

---

guidebooks/ml/codeflare/training/byot/base-ray-image.md
guidebooks/ml/codeflare/training/byot/index.md
guidebooks/ml/codeflare/training/byot/working-directory.md
guidebooks/ml/codeflare/training/index.md

additional flow added to training to support the ability to bring your own training repo and use that. the training repo is assumed to be derived from template https://github.com/guidebooks/codeflare-template-repo
https://github.com/guidebooks/store/compare/main...atinsood:store:custom_application_merged_v2?expand=1#diff-96e85c3f0a2a6b9054ac677dc591552fd1004314264fbd2bb170e14f46215e35R23 is the entry point

feat:bring your own training

---

guidebooks/ml/ray/cluster/kubernetes/is-ready.md

This PR adds an emit of the initial state.

fix: ml/ray/cluster/kubernetes/is-ready emits nothing if the cluster is not ready

---

guidebooks/ml/ray/start/kubernetes/port-forward.md
guidebooks/ml/ray/start/kubernetes/port-forward/mlflow.md

currently, we have combined the ray helm chart and the mlflow pod into a single helm chart. we need to fix that. for now, this PR at least allows this case (starting up the mlflow port forward when the ray cluster is not up) to at least function.

fix: starting guidebooks/ml/ray/start/kubernetes/port-forward/mlflow may fail if ray cluster is not up

---

guidebooks/util/shuf.md

Done: A very minor fix
Todo before merge:
To enable the 'laptop to cloud' workflow in Ray, Apple Silicon users will need to use Conda locally due to the `grpcio` dependency. See the [Ray docs Apple Silicon explanation](https://docs.ray.io/en/latest/ray-overview/installation.html#m1-mac-apple-silicon-support).
Without this addition, the current behavior crashes on _step 5: Run a Ray Job_ of `ml/ray/run`.
```
$ codeflare ml/ray/run
✔  Choice 5: Run a Ray Job  · Example: Using Ray Tasks to Parallelize a Function
▶ Ray Core: Parallelizing Functions with Ray Tasks
ImportError:
Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for …
```

Improving ml/ray/run experience on MacOS & Apple Silicon M1

---

guidebooks/ml/codeflare/training/bert/index.md

we now support launching the tensorboard separately

fix: ml/codeflare/training/bert no longer needs to launch a local tensorboard

---

guidebooks/ml/ray/run/core/actors.md
guidebooks/ml/ray/run/core/tasks.md
guidebooks/ml/ray/run/index.md
guidebooks/ml/ray/run/logs.md
guidebooks/ml/ray/run/serve/examples/gradient-boosting.md
guidebooks/ml/ray/run/train/examples/pytorch/index.md
guidebooks/ml/ray/run/tune/examples/grid-search.md

we are importing ml/ray/start before util/jobid

fix: ml/ray/run demo guidebooks do not properly initialize jobid

---

guidebooks/ml/codeflare/run.md
guidebooks/ml/codeflare/training/byot/base-ray-image.md
guidebooks/ml/codeflare/training/byot/index.md
guidebooks/ml/codeflare/training/index.md

This PR also updates the byot index.md to leverage new support from the `ray-submit` intrinsic, for passing working dir.
This PR also renames "Fine Tuning" to "Fine Tuning Demos", same for "Training" to "Training Demos"

chore: refactor bring your own training to top-level of ml/codeflare

---

guidebooks/aws/_auth.md
guidebooks/aws/auth.md
guidebooks/aws/choose/profile.md

- we had been assuming that the ~/.aws/credentials file had only one credential pair
- and had been hard-coding an s3 endpoint
on the latter, there isn't a supported solution for this yet (https://github.com/aws/aws-cli/issues/1270). lacking a supported solution, this PR for now assumes that the ~/.aws/config section may have an `endpoint_url=` conf entry.

feat: improve support for arbitrary s3 endpoints and for multiple aws profiles

---

guidebooks/aws/auth.md
guidebooks/aws/choose/profile.md

we are currently only using this for internal consumption, whereas many clis and libraries use that env var value

fix: avoid setting the "official" AWS_PROFILE env var

---

guidebooks/ml/ray/start/kubernetes.md

We were using `kubectl wait --for=condition=Ready` with a label-selector. The `kubectl` behavior with this combination is to wait for *all* pods to have that condition. Thus, if just one pod has died, at any point in the past, and is thus in an Error state, or perhaps Completed state... the guidebook hangs.
This PR switches to use polling. I don't see how we can use `kubectl wait` with some sort of exclusion.  ref: https://github.com/kubernetes/kubernetes/issues/87747
Also, the `--for=jsonpath` does not support negation (i had thought to use a !=Pending... which is really what we want).
Also with this PR, the guidebook will succeed when at least one pod is Ready. Previously, we would wait for *all* pods to be ready. Probably a good thing, too?

fix: ml/ray/start/kubernetes can hang if a ray worker pod has died

---

guidebooks/ml/tensorboard/start/kubernetes/chart/templates/tensorboard.yaml

This PR pins to starpit/tensorboard:0.0.1

fix: tensorboard in kubernetes should pin a version

---

guidebooks/ml/ray/start/kubernetes.md

As with https://github.com/guidebooks/store/pull/244

fix: ml/ray/start/kubernetes can hang if a ray head pod has died

---

guidebooks/ml/ray/run/logs.md

This PR switches over to a rather simpler curl command, to avoid a requirement of the `ray` CLI just to poll for the status of a job.

fix: avoid use of ray CLI for ray job status poll in ml/ray/run/logs

---

guidebooks/kubernetes/choose/ns.md
guidebooks/kubernetes/context.md
guidebooks/ml/mlflow/start/kubernetes/install.md
guidebooks/ml/mlflow/start/kubernetes/port-forward.md
guidebooks/ml/mlflow/stop/kubernetes/index.md
guidebooks/ml/ray/cluster/kubernetes/is-installed.md
guidebooks/ml/ray/cluster/kubernetes/is-ready.md
guidebooks/ml/ray/hacks/openshift/uid-range.md
guidebooks/ml/ray/run/job-definition.md
guidebooks/ml/ray/start/kubernetes.md
guidebooks/ml/ray/start/kubernetes/install-via-helm.md
guidebooks/ml/ray/start/kubernetes/port-forward/ray.md
guidebooks/ml/ray/stop/kubernetes.md
guidebooks/ml/tensorboard/start/kubernetes/install.md
guidebooks/ml/tensorboard/start/kubernetes/port-forward.md
guidebooks/ml/tensorboard/stop/kubernetes/index.md
guidebooks/ml/tensorflow/tensorboard/rsync.md
guidebooks/s3/create/kubernetes/secret.md

And the same for `-n ${KUBE_NS}` to `${KUBE_NS_ARG}`.
This allows us to run in situations where we do not want to set any `--context` or `-n` options. For example, when running inside a kubernetes cluster, `kubectl` is smart enough to pick up this information automatically. I don't see any way to pass some kind of fake context name in-cluster. For namespace... this *is* knowable, even in-cluster, but I figured we should make this change uniformly here.

fix: change `--context ${KUBE_CONTEXT}` to `${KUBE_CONTEXT_ARG}`

---

guidebooks/ml/ray/cluster/index.md

Maybe this was a leftover from earlier versions which did require it.

fix: ml/ray/cluster does not need the ray CLI

---

guidebooks/ml/ray/aggregator/in-cluster/client-side/aggregator.yaml
guidebooks/ml/ray/aggregator/in-cluster/client-side/start/with-jobid.md

We had been using a GUIDEBOOK set in the aggregator.yaml. It will be clearer to pass this through explicitly in the command line in ml/ray/aggregator/in-cluster/client-side/start/with-jobid.md

fix: ml/ray/aggregator/in-cluster/client-side should use guidebook on command line

---

guidebooks/ml/ray/run/logs/via-websocat.md

1) we check for status=SUCCEEDED, but it should be status!=RUNNING
2) our comparison uses jq, but should use jq -r

fix: ml/ray/run/logs/via-websocat done poller issues

---

guidebooks/ml/ray/run/gpu-utilization.sh
guidebooks/ml/ray/run/node-stats.sh
guidebooks/ml/ray/run/pod-stats.sh
guidebooks/ml/ray/run/pod-vmstat-memory.sh
guidebooks/ml/ray/run/pod-vmstat.sh

If the client-side starts streaming before the server-side has any data, the tail -f's will exit and never recover.
This PR introduces a script `wait-for-and-tailf` which relies on `inotifywait` (part of `inotify-tools` for ubuntu) to wait for a file to exist (using push notifications from inotify), and then start tailing.
TODO: how can we get this utility into the store?

fix: client-side of in-cluster log aggregator may fail to stream certain content

---

guidebooks/ml/ray/run/logs/init.md

we were checking the existence of the enclosing directory for the job, but this may already exist, even for the first run. in this pr, we instead check for the presence of the jobid.txt file.

fix: aggregator singleton check does not work

---

guidebooks/ml/codeflare/training/bert/index.md
guidebooks/ml/codeflare/training/byot/index.md
guidebooks/ml/codeflare/training/demos/mlflow/index.md
guidebooks/ml/codeflare/training/demos/tensorboard/index.md
guidebooks/ml/codeflare/tuning/glue/index.md
guidebooks/ml/ray/run/core/actors.md
guidebooks/ml/ray/run/core/tasks.md
guidebooks/ml/ray/run/data/create/from-file.md
guidebooks/ml/ray/run/data/create/from-range.md
guidebooks/ml/ray/run/serve/examples/gradient-boosting.md
guidebooks/ml/ray/run/train/examples/pytorch/index.md
guidebooks/ml/ray/run/tune/examples/grid-search.md

With this change, the main ray runners do not launch the log aggregator. We may want to revisit this at some point, e.g. so that the aggregator is launched upon job submission, so that all of the resource and event metrics are collected.
However, that will be a separate change, because, as it stands, the ray runners do not launch the aggregator proper, but instead point to a guidebook a bit deeper (`ml/ray/run/logs`; one that the aggregator also uses). 
So... with the switch to a server-side log aggregator, some change here is needed. I have decided to make that change in two passes. First, in this PR, the run launching guidebooks will not call that "internal" guidebook. Later, we can consider having them instead use the aggregator proper.

feat: update ray runners not to start up aggregator

---

guidebooks/kubernetes/choose/ns.md

in locked down openshift clusters, users may not be able to list namespaces, but they can list projects.

fix: kubernetes/choose/ns fails if ns permission denied, but oc get projects works

---

guidebooks/ml/ray/start/kubernetes/chart/templates/_head-deployment.tpl
guidebooks/ml/ray/start/kubernetes/chart/templates/_worker-deployment.tpl
guidebooks/ml/ray/start/kubernetes/chart/values.yaml
guidebooks/ml/ray/start/kubernetes/install-via-helm.sh

This should allow use of lightweight images, such as `python:3.8-slim`. The head and worker nodes will detect the absence of the `ray` pip, and install it if needed.
This PR also:
- adds a missing readiness probe to the ray helm chart's head container
- allows the helm chart REPO, ORG, and BRANCH to be specified by env vars: RAY_CHART_ORG, etc.

feat: allow "keep it simple" ray charts to install ray cli on demand

---

guidebooks/ml/ray/start/kubernetes/install-via-helm.sh

this is a regression from the recent "keep it simple" work. we were no longer passing through the desired operator image to the helm chart.

fix: ml/ray/start/kubernetes/install-via-helm broken w.r.t. ray operatorImage

---

guidebooks/ml/ray/start/kubernetes/install-via-helm.sh

This points to starpit/ray#operator-cpu, which also adds support for specifying operator resources via template.

feat: pin a branch for the default ray helm chart

---

guidebooks/ml/ray/start/kubernetes.md

We were using the default of 30s; this PR increases the wait timeout to 240s

fix: increase pod readiness wait timeout in ml/ray/start/kubernetes

---

guidebooks/kubernetes/choose/ns.md
guidebooks/kubernetes/context.md

this helps with testing, so that the test rig can specify the in-cluster context and namespace strings; in-cluster, these strings are arbitrary

fix: allow in-cluster operation to specify a default context and namespace name

---

guidebooks/ml/ray/start/kubernetes/install-via-helm.sh

Oof, mcad currently has a bug that forces us to state explicitly the target namespace in all of our resources. When running in-cluster, it may be difficult to intuit this name, especially under test scenarios (where, in order to use a fixed namespace for the guidebook profile (the answer to the "namespace" question).
This PR allows clients to set a KUBE_NS_FOR_REAL env var that will be used just for this scenario. Once mcad fixes its bug, i think we can back this out.

fix: allow splicing in of namespace in ray helm chart

---

guidebooks/ml/ray/aggregator/in-cluster/client-side/aggregator.yaml

so that ml/ray/run/node-stats works

fix: add nodes to the log aggregator Role

---

guidebooks/ml/ray/aggregator/in-cluster/client-side/aggregator.yaml
guidebooks/ml/ray/run/logs.md

This requires cluster scope privileges, which for not we should not assume.

fix: disable node-stats.sh collection in log aggregator

---

guidebooks/ml/ray/aggregator/in-cluster/server-side/setup.md
guidebooks/ml/ray/aggregator/setup.md

1) head node wait should specify the same timeout we use elsewhere (240s); the default is 30s
2) server-side also needs to wait for the job to start before proceeding

fix: two more fixes for log aggregator not waiting long enough

---

guidebooks/ml/codeflare/tuning/glue/pip.txt
guidebooks/ml/ray/install/cli.md
guidebooks/ml/ray/start/local.md

we have been floating our ray dependencies. 1.14 just came out with some breaking changes. we need to fix those, but we also need to avoid random breaking changes in the future. so, for now, we will pin to 1.13.

fix: pin ray (to 1.13)

---

guidebooks/ml/ray/aggregator/setup.md

with recent fixes, it was at least now waiting for the job to appear in the ray api, but we need to wait for it to be actually running, rather than pending

fix: server-side aggregator needs to wait for job to be actually running

---

guidebooks/ml/ray/run/logs.md

oof, this caused a downstream regression. some paths actually still need the path that uses the ray cli to stream out job logs.
offending PR: https://github.com/guidebooks/store/pull/345
Rather than reverting that commit, we will patch back in the logic, since there was a useful change in that PR.

fix: restore ray cli-based log streaming

---

guidebooks/ml/codeflare/training/roberta/index.md

This is because this guidebook manages the input file without any help from madwizard.

fix: update ml/codeflare/training/roberta to specify --no-input to ray-submit intrinsic

---

guidebooks/ml/codeflare/training/roberta/index.md

- ML_CODEFLARE_ROBERTA_GITHUB
- ML_CODEFLARE_ROBERTA_ORG
- ML_CODEFLARE_ROBERTA_REPO
- ML_CODEFLARE_ROBERTA_BRANCH
- ML_CODEFLARE_ROBERTA_SUBDIR
where the git clone looks like:
```
git@${ML_CODEFLARE_ROBERTA_GITHUB}:${ML_CODEFLARE_ROBERTA_ORG}/${ML_CODEFLARE_ROBERTA_REPO}.git
```
or will look like this, if two additional env vars are defined (ML_CODEFLARE_ROBERTA_GITHUB_USER, ML_CODEFLARE_ROBERTA_GITHUB_TOKEN):
```
https://${ML_CODEFLARE_ROBERTA_GITHUB_USER}:${ML_CODEFLARE_ROBERTA_GITHUB_TOKEN}@${ML_CODEFLARE_ROBERTA_GITHUB}/${ML_CODEFLARE_ROBERTA_ORG}/${ML_CODEFLARE_ROBERTA_REPO}.git
```

fix: allow roberta github location defaults to be overridden

---

guidebooks/ml/codeflare/training/demos/getting-started/main.py

fix: add a marker to the end of the getting-started guidebook

---

guidebooks/ml/codeflare/training/roberta/wrapper.sh

we were using the COS "direct" endpoint, which only works within ibmcloud. this PR adds detection of whether we should use the direct of public COS endpoint.

fix: update ml/codeflare/training/roberta to work outside of ibmcloud

---

guidebooks/ml/ray/start/kubernetes/chart/templates/_head-deployment.tpl
guidebooks/ml/ray/start/kubernetes/chart/templates/head-serviceaccount.yaml

To allow the head pod to list worker pods

feat: associate ray head pod with a serviceaccount

---

guidebooks/ml/codeflare/training/roberta/wrapper.sh

To allow for running the demo on a 16GiB GPU, this PR lowers the b_size from 32 to 16. This is just for the demo/sample input scenario.

fix: in ml/codeflare/training/roberta, lower b_size for sample input

---

guidebooks/ml/ray/start/kubernetes/port-forward/ray.md
guidebooks/ml/ray/stop/kubernetes.md

This PR adds a loop around the port forward, because the client side connection to the server will inevitably time out. The sleep is there to protect us from unforeseen bugs that might otherwise result in an infinite spin loop.
It also includes some minor cleanups to the imports.

fix: ml/ray/start/kubernetes/port-forward/ray should retry

---

guidebooks/ml/ray/start/kubernetes/chart/templates/_worker-deployment.tpl

i.e. remove the cpu limit from the ray worker deployment

fix: allow ray workers to use as much cpu as they need, if available

---

guidebooks/kubernetes/choose/ns.md
guidebooks/ml/mlflow/start/kubernetes/install.md
guidebooks/ml/mlflow/start/kubernetes/port-forward.md
guidebooks/ml/ray/cluster/kubernetes/is-ready.md
guidebooks/ml/ray/start/kubernetes.md
guidebooks/ml/tensorboard/start/kubernetes/install.md
guidebooks/ml/tensorboard/start/kubernetes/port-forward.md

we had a few cases of `kubectl --context foo get pods` (or some such); i'm not entirely sure, but i think that some versions of kubectl are not happy with options coming before the verb.

fix: kubectl context and namespace args have to be after verb

---

guidebooks/kubernetes/choose/ns.md

the `kubernetes/choose/ns` option to create a namespace is not validating that the namespace already exists

fix: if user selects "create namespace", then profile can get stuck

---

guidebooks/kubernetes/coscheduler/install/coscheduler.sh
guidebooks/kubernetes/mcad/install/mcad.sh
guidebooks/ml/codeflare/training/roberta/clone.sh
guidebooks/ml/mlflow/start/kubernetes/install.sh
guidebooks/ml/ray/start/kubernetes/install-via-helm.sh
guidebooks/ml/tensorboard/start/kubernetes/install.sh

ugh, it looks like git had a horrible bug in its git checkout --sparse when you use a url, and of course broken versions of git seem to be fairly common  — e.g. a broken version was installed in my ubuntu-on-WSL2 by default.
we were using git clone --sparse https://somethingsomething, which git 2.25 does not like. This PR switches us to a form that seems to work with 2.25 and later versions as well (2.37.x tested).
all of our automated tests apparently were using a version without this git bug.

fix: improve git compatibility with sparse checkout

---

guidebooks/ml/ray/install/cli.md
guidebooks/ml/ray/install/data.md
guidebooks/ml/ray/install/serve.md
guidebooks/ml/ray/install/tune.md
guidebooks/ml/ray/start/local.md
guidebooks/python/pip/aiorwlock.md
guidebooks/python/pip/boto3.md
guidebooks/python/pip/fastapi.md
guidebooks/python/pip/pyarrow.md
guidebooks/python/pip/ray_lightning.md
guidebooks/python/pip/scikit-learn.md
guidebooks/python/pip/tabulate.md
guidebooks/python/pip/tensorboard.md
guidebooks/python/pip/tensorflow.md
guidebooks/python/pip/torch.md
guidebooks/python/pip/torch_lightning.md
guidebooks/python/pip/torchvision.md
guidebooks/python/pip/tqdm.md
guidebooks/python/pip/uvicorn.md

This should help us avoid issues with pip versus pip3, and thus avoid the need to install on linux (e.g.) python-is-python3
Also make sure to use --user consistently.

fix: use pip3 rather than pip to install deps

---

guidebooks/ml/codeflare/training/roberta/wrapper.sh

For some reason our check `$? = 4` is failing because `$?` is empty. I don't know why.

fix: ml/codeflare/training/roberta fails to fetch sample data in non-ibm clouds

---

guidebooks/ml/codeflare/training/roberta/wrapper.sh

Since the logdir isn't important for the sample run, let's use the path that has the highest chance of working versus permissions. The default in the roberta python code is currently /home/ray/ which might not be accessible in certain clusters.

fix: roberta with sample input should use /tmp for logdir

---

guidebooks/ml/ray/start/kubernetes.md
guidebooks/ml/ray/start/kubernetes/install-via-helm.md

this PR moves those dependences down to install-via-helm

fix: ml/ray/start/kubernetes expresses import dependencies that aren't directly needed

---

guidebooks/util/envsubst.md
guidebooks/util/envsubst2.md

The former uses the GNU version; the latter uses https://github.com/a8m/envsubst (MIT licensed).

feat: add util/envsubst and util/envsubst2

---

guidebooks/ml/codeflare/index.md
guidebooks/ml/codeflare/run-with-codeflare.md
guidebooks/ml/codeflare/run.md
guidebooks/ml/codeflare/training/demos/index.md
guidebooks/ml/codeflare/training/index.md
guidebooks/ml/codeflare/training/roberta/choose-data.md
guidebooks/ml/codeflare/tuning/index.md
guidebooks/ml/mlflow/start/index.md
guidebooks/ml/ray/cluster/index.md
guidebooks/ml/ray/run/core/index.md
guidebooks/ml/ray/run/data/create/index.md
guidebooks/ml/ray/run/data/index.md
guidebooks/ml/ray/run/index.md
guidebooks/ml/ray/run/serve/index.md
guidebooks/ml/ray/run/train/examples/pytorch/index.md
guidebooks/ml/ray/run/train/index.md
guidebooks/ml/ray/run/tune/index.md
guidebooks/ml/ray/stop/index.md
guidebooks/ml/tensorboard/start/index.md
package-lock.json
package.json

(not always, only for guidebooks that are importing other guidebooks that offer choice)

feat: bump to madwizard 1.0.0 which mandates use of imports versus inlining

---

guidebooks/kubernetes/kind.md

Previously, kubernetes/kind only checked whether kind was installed

fix: update kubernetes/kind to install kind if needed

---

guidebooks/util/spinner/guidebook-spinner.sh

fix: util/spinner may not hide cursor in non-pty stdouts

---

guidebooks/ml/ray/start/kubernetes/chart/templates/_head-deployment.tpl
guidebooks/ml/ray/start/kubernetes/chart/templates/_worker-deployment.tpl
guidebooks/ml/ray/start/kubernetes/chart/values.yaml
guidebooks/ml/ray/start/kubernetes/install-via-helm.sh

This PR:
- Enables the user to change the `imagePullPolicy` value. In cases where the images have been update outside the cluster (and have the same tag used in the cluster), this will allow the image to be replaced with the newer version of the same image.
- Adds environment variable to specify the location of the RayChart if the default is not wanted

Enable users to change imagePullPolicy in the YAML file

---

guidebooks/s3/choose/instance-maybe.md
guidebooks/s3/choose/instance.md

Instead of "my provider is aws", say "my credentials are stored on my laptop using the aws ~/.aws/credentials convention"

fix: update the terminology around choosing s3 credentials

---

guidebooks/ml/codeflare/training/roberta/choose-data.md

tabs whose first paragraphs have links may appear truncated after that first link, if there is not a newline separating the tab from the body

fix: workaround for madwizard bug in ml/codeflare/training/roberta/choose-data-public

---

guidebooks/ml/ray/start/kubernetes/port-forward/ray.md

There was a typo in the script. The `sleep 1` was not being executed if the ray cluster was not reachable.

fix: ml/ray/start/kubernetes/port-forward/ray causes cpu spinloop

---

guidebooks/ml/ray/start/kubernetes/install-via-helm.md

BREAKING CHANGE: this is a major update to the ray api

feat: bump default ray image to 2.1.0 (from 1.13.0)

---

guidebooks/ibm/cloud/ce/project.md
guidebooks/ibm/cloud/target.md
guidebooks/kubernetes/context.md
guidebooks/kubernetes/hosted-kubernetes.md
guidebooks/ml/ray/start/kubernetes/chart/templates/_head-deployment.tpl
guidebooks/ml/ray/start/kubernetes/chart/templates/_worker-deployment.tpl
guidebooks/ml/ray/start/kubernetes/chart/templates/head-serviceaccount.yaml
guidebooks/ml/ray/start/kubernetes/chart/values.yaml
guidebooks/ml/ray/start/kubernetes/install-via-helm.sh

1) Revert ray helm charts from job back to deploy. Some hosted kubernetes do not support jobs.
2) codeengine request that request==limit
3) codeengine does not support binary units e.g. Gi, it only supports G
4) ImagePullPolicy must be Always :(

feat: allow use of ibmcloud codeengine for kubernetes context selection

---

guidebooks/ml/codeflare/training/roberta/submit.md
guidebooks/ml/ray/cluster/choose/index.md
guidebooks/ml/ray/cluster/choose/kubernetes.md
guidebooks/ml/ray/start/kubernetes.md
guidebooks/ml/ray/start/kubernetes/chart/templates/_head-deployment.tpl
guidebooks/ml/ray/start/kubernetes/install-via-helm.sh
guidebooks/ml/ray/stop/kubernetes.md

We had been using a fixed name for the ray cluster. This was fine before we tore down the ray cluster upon job completion. Now that we do so, we will need to use a variable ray cluster name (and helm chart name) per job.

feat: ray cluster name should vary by job

---

guidebooks/ml/ray/cluster/choose/kubernetes.md

We were assuming a label structure that ray.org's helm chart does not have.

fix: ml/ray/cluster/choose does not work against ray's helm chart

---

guidebooks/ml/ray/run/pod-vmstat-memory.sh

with this PR, hopefully that guidebook now supports both v1 and v2 apis

fix: ml/ray/run/pod-vmstat-memory does not support cgroup v2 api

---

guidebooks/kubernetes/choose/secret/image-pull.md
guidebooks/ml/codeflare/training/byoc/index.md

BREAKING CHANGE: rename kubernetes/secrets/image-pull to kubernetes/choose/secret/image-pull

fix: kubernetes image-pull can hang if cluster is not reachable

---

guidebooks/ml/codeflare/training/byoc/index.md
guidebooks/ml/codeflare/training/byoc/submit.md
guidebooks/ml/codeflare/training/demos/getting-started/index.md
guidebooks/ml/codeflare/training/demos/getting-started/submit.md
guidebooks/ml/codeflare/training/roberta/_roberta.md
guidebooks/ml/codeflare/training/roberta/submit.md

ugh, for now finally blocks are not executed after code blocks within the given file. i think this is a general problem with imports; they are always executed before any code blocks in that same file, even for `:import{}` inline imports (rather than topmatter imports).

fix: work around finally ordering issue

---

guidebooks/ml/ray/stop/kubernetes/with-known-cluster-name.md

Hmm, if you ctrl+c a helm install before it has gotten very far, and then immediately issue a helm uninstall, the uninstall may fail, even though the install (a second or two later) leaves a dangling (broken) helm chart in your cluster.
This PR retries a few times...

fix: helm uninstall (ray stop) issued immediately after helm install can leave dangling helm

---

guidebooks/s3/choose/s3fs/kubernetes/pvc.md

Kubernetes does not allow an apply-update over an existing PVC if the storage class has changed. This PR tries to detect this situation and deletes the old PVC, if this is the case.

fix: s3/choose/s3fs/kubernetes may fail to create pvc

---

guidebooks/s3/choose/s3fs/kubernetes/init.md

Otherwise, two jobs in the same namespace, but that need access to different s3 data, will collide.

fix: s3fs secret and claim name should hash in cluster name

---

guidebooks/ml/ray/run/pod-vmstat-memory.sh
guidebooks/ml/ray/run/pod-vmstat.sh

BREAKING CHANGE: this breaks any clients that were assuming a normal vmstat format for the cpu stats. it is now limited to the cpu columns (i.e. us sy id wa st).

feat: improve console readability of ml/ray/run/pod-vmstat and memory stats

---

guidebooks/ml/ray/cluster/kubernetes/choose-pod-scheduler.md

BREAKING CHANGE: this removes support for using the ray operator. There is some breaking skew in ray 2 that we have not accounted for in our fork of the ray helm chart.

feat: remove ray autoscaler option in ml/ray/cluster/kubernetes/choose-pod-scheduler

---

guidebooks/ml/ray/run/gpu-utilization.md
guidebooks/ml/ray/run/gpu-utilization.sh
guidebooks/ml/ray/run/pod-stats.md
guidebooks/ml/ray/run/pod-stats.sh
guidebooks/ml/ray/run/pod-vmstat-memory.sh
guidebooks/ml/ray/run/pod-vmstat.sh
guidebooks/ml/ray/start/kubernetes/label-selectors.md

One only needs to specify the label selector that identifies the pods to be tracked.
e.g.
```shell
WAIT=true KUBE_POD_LABEL_SELECTOR='ray-cluster-name=nickm-c887b3d7-73f3-46ea-a427-7242e6ed459c' codeflare ml/ray/run/pod-stats
```

feat: allow use of vmstat and gpu utilization tracking outside of ray

---

guidebooks/ml/ray/run/gpu-utilization.md

If `NUM_GPUS=""` i.e. an empty string, then our if check fails in zsh

fix: gpu-utilization.md may fail on zsh if profile specifies no gpus

---

guidebooks/ml/ray/start/kubernetes/events.md

1) trim off job uuid
2) trim off age
3) add [Cluster Event] line prefix
4) don't use -o wide
5) use a dim/cyan color

fix: kube events lines are way too wide

---

guidebooks/ml/ray/start/kubernetes/chart/templates/_head-deployment.tpl
guidebooks/ml/ray/start/kubernetes/chart/templates/workdir.yaml
guidebooks/ml/ray/start/kubernetes/install-via-helm.sh

With this change, we instead use a volume and volumeMount to transmit the workdir to the pod. Unfortunately, this still requires base64-encoding the workdir in the configmap, as it is not possible to store binary data in a configmap.

fix: avoid use of env vars for workdir tarball

---

guidebooks/ml/ray/run/pod-vmstat-memory.sh
guidebooks/ml/ray/run/pod-vmstat.sh

This also should fix the warning that Winteractive is not a known option on linux/gnu awk.

feat: move cpu and memory utilization to be first column

---

guidebooks/ml/codeflare/run.md
guidebooks/ml/torchx/run/index.md

BREAKING CHANGE: this changes the menu structure for ml/codeflare/run, which may require test updates.
BREAKING CHANGE: this also removes the old "codeflare model architecture" option from ml/codeflare/run

feat: add torchx/run to ml/codeflare/run

---

guidebooks/ml/torchx/run/start.sh
guidebooks/ml/torchx/run/submit.md

Note: the kubernetes_mcad torchx scheduler still does not yet support a "keep it simple" approach.

fix: allow ml/torchx/run to choose pod scheduler

---

guidebooks/ml/ray/start/kubernetes/chart/templates/_worker-deployment.tpl

Without this, the Job controller schedules one pod at a time. If the coscheduler is used (gang scheduling via PodGroup), then... there is a lockup.

fix: specify parallelism for ray worker Job

---

guidebooks/ml/ray/aggregator/setup.md

which means we cannot collect any pre-run logs! or gpu/cpu utilization while the setup is in process

fix: log setup ends up waiting for job to be running

---

guidebooks/openshift/oc.md

From 4.10.33. This fixes "Killed 9" on apple silicon. ref: https://bugzilla.redhat.com/show_bug.cgi?id=2059125

fix: bump openshift/oc to 4.12.9

---

guidebooks/ml/codeflare/training/demos/getting-started/submit.md
guidebooks/ml/ray/aggregator/setup.md
guidebooks/ml/ray/run/logs.md
guidebooks/ml/ray/run/logs/via-websocat.md
guidebooks/ml/ray/run/pod-vmstat-memory.sh
guidebooks/ml/ray/run/pod-vmstat.sh
guidebooks/ml/ray/run/runtime-env-agent.sh
guidebooks/ml/ray/run/runtime-env-setup.md
guidebooks/ml/ray/run/runtime-env-setup.sh
guidebooks/ml/ray/run/status-poller.md
guidebooks/ml/ray/run/status-poller.sh
guidebooks/ml/ray/start/kubernetes/chart/templates/_head-deployment.tpl
guidebooks/ml/ray/start/kubernetes/events.md
guidebooks/ml/ray/start/kubernetes/events.sh
guidebooks/ml/ray/start/kubernetes/install-via-helm.sh
guidebooks/ml/ray/start/kubernetes/pods.sh
guidebooks/ml/ray/start/kubernetes/wait-for-head.md
guidebooks/ml/ray/start/kubernetes/wait-for-workers.md
guidebooks/ml/torchx/run/wait-till-running.md

- tracking of ray pip installs
- tracking of pod status
- more consistent prefixing of these streams
- wait for head/worker output cleanup (less noisy "Waiting for Ray Head....")
- removes ray job env capture, as it was not working and resulted in errors in the output
- cpu/mem/gpu streams now are not tee'd to stdout, only captured to the files

fix: major cleanups to job log streaming

---

guidebooks/ml/ray/start/kubernetes/chart/templates/_head-deployment.tpl

apparently, re: nvidia.com/gpu requests/limits, on nodes with 8 gpus:
no request: get 8, according to nvidia-smi, but 0 according to kubectl get quota
request 0: same
request 1: get 1, according to nvidia-smi *and* kubectl get quota
oof, so for now we need to assign gpus to the head, if we are assigning them to the worker.
i'm not sure what happens when using a gpu-enabled image but not desiring to use gpus... we'll have to cross that bridge when we come to it

fix: assign gpus to ray head, if we are assigning them to workers

---

guidebooks/ml/ray/start/kubernetes/port-forward/ray-with-cluster.md

this fixes non-sleepy spinlooping
it also fixes the situation where the pod is no longer running, and gives up rather than emit bad errors

fix: ray port-forward may spin loop

---

guidebooks/ml/ray/run/logs.md
guidebooks/ml/ray/start/kubernetes.md

this means we cannot extract any env info during setup

fix: ray jobs emit job env.json only after job is running

---

guidebooks/ml/ray/run/logs/via-websocat.md

it seems we no longer need the polling complexities; this also fixes a few bugs that come up if the helm chart is deleted in a race window in this polling logic

fix: websocat ray log streaming can be simplified

---

guidebooks/ml/ray/start/kubernetes/custodian/custodian.yaml
guidebooks/ml/ray/start/kubernetes/custodian/index.md
guidebooks/ml/ray/start/kubernetes/label-selectors.md

this helps to support non-ray runs. this also gives us smoother streaming of logs, as we leverage the use of websocat in the ray head

fix: logs custodian should pull from kubectl logs, not ray job logs

---

guidebooks/ml/ray/start/kubernetes/custodian/custodian.yaml

this also removes the RAY_ADDRESS env var from the logs pod, as it is no longer needed (we now use `kubectl logs` to stream out the logs)

fix: lower custodian logs container 100m/128Mi -> 50m/32Mi

---

guidebooks/ml/codeflare/custodian/containers/cpu/container.yaml
guidebooks/ml/codeflare/custodian/containers/cpu/cpu.sh
guidebooks/ml/codeflare/custodian/containers/gpu/container.yaml
guidebooks/ml/codeflare/custodian/containers/gpu/gpu.sh
guidebooks/ml/codeflare/custodian/containers/logs/container.yaml
guidebooks/ml/codeflare/custodian/containers/mem/container.yaml
guidebooks/ml/codeflare/custodian/containers/mem/memory.sh
guidebooks/ml/codeflare/custodian/index.md
guidebooks/ml/ray/start/kubernetes/name.md

We had been using a fixed amount of memory for the cpu/mem/gpu trackers. But these need memory per worker (since we connect to each worker).
This also updates the `kubectl logs` in the logs container to pass in a `--max-logs-requests` that is set to num workers for the run.
This also fixes some issues with the custodian vs torchx jobs, to avoid tracking worker status and runtime env setup (since, for now, those are ray-specific).

fix: improve custodian memory requests for larger jobs

---

guidebooks/ml/codeflare/custodian/containers/logs/container.yaml

if there is a network disconnect, we cannot delete the job resources
this is a short-term fix. the real fix is to figure out how to be more resilient to network disconnects.

fix: avoid helm delete in custodian for now

---

guidebooks/ml/ray/start/kubernetes/chart/templates/_head-deployment.tpl
guidebooks/ml/ray/start/kubernetes/chart/templates/_worker-deployment.tpl
guidebooks/ml/ray/start/kubernetes/install-via-helm.sh
guidebooks/ml/torchx/run/invoke-torchx.sh

With this PR, we no longer hard-wire the name of the multinic resource, but we are always choosing the first one. TODO: do we need to make this (yet another) choice? so that the user chooses with multinic resource to use? hmm

fix: multinic detection was broken; also was hard-wiring name of resource

---

guidebooks/ml/ray/start/kubernetes/chart/templates/pvc.yaml

Prevent s3fs from utilizing all available disk space for cache.  Sets min available free space to 20GB on the filesystem being used to cache reads from COS.

Update pvc.yaml - add diskfree parameter

---

guidebooks/kubernetes/mcad/install/mcad.sh
guidebooks/ml/ray/start/kubernetes/chart/templates/_head-deployment.tpl
guidebooks/ml/ray/start/kubernetes/chart/templates/_worker-deployment.tpl
guidebooks/ml/ray/start/kubernetes/chart/templates/ray.yaml
guidebooks/ml/torchx/install/cli.md
guidebooks/ml/torchx/install/path.md
guidebooks/ml/torchx/run/instance-label.md

Summary: MCAD V1.34.1 changed the Appwrapper crd. 
This PR updates:
- appwrapper.mcad.ibm.com -> appwrapper.workload.codeflare.dev
- Any group API indicators to workload.codeflare.dev
- MCAD installation to v1.34.1, including controller repository and image
- TorchX and related dependencies to TorchX=0.6.0 which will feature MCAD V1.34.1 support

feat: Update to mcad v1.34.1 support and torchx 0.6.0
